name: Checkout Holdex Github Actions
description: Checks out holdex/github-actions at a given ref into .holdex-actions

inputs:
  ref:
    description: Ref to checkout
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Holdex Github Actions
      uses: actions/checkout@v4
      with:
        repository: teodorus-nathaniel/personal-actions
        ref: ${{ inputs.ref }}
        path: .holdex-actions
