name: PR Checks
description: Run selected PR checks in a single job

inputs:
  run-prettier:
    description: Run Prettier check
    required: false
    default: "true"
  run-markdown:
    description: Run Markdown check
    required: false
    default: "true"
  run-commits:
    description: Run Commit check
    required: false
    default: "true"
  package-manager:
    description: Package manager to use (bun or pnpm)
    required: false
    default: "bun"

runs:
  using: composite
  steps:
    - shell: bash
      run: 'echo "action_ref ${{ github.action_ref }}"'
    - shell: bash
      run: 'echo "workflow_sha ${{ github.workflow_sha }}"'
    - name: Checkout shared actions repository
      uses: actions/checkout@v4
      with:
        repository: holdex/github-actions
        ref: ${{ github.action_ref || github.workflow_sha }}
        path: .github-actions-source

    - name: Setup runtime
      if:
        (github.event_name != 'pull_request' || github.event.pull_request.draft
        != true) && (inputs.run-prettier != 'false' || inputs.run-markdown !=
        'false' || inputs.run-commits != 'false')
      uses: ./.github-actions-source/.github/actions/setup-runtime
      with:
        package-manager: ${{ inputs.package-manager }}

    - name: Get changed files
      id: changed-files
      if:
        (github.event_name != 'pull_request' || github.event.pull_request.draft
        != true) && (inputs.run-prettier != 'false' || inputs.run-markdown !=
        'false')
      uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323

    - name: Run Prettier check
      if:
        (github.event_name != 'pull_request' || github.event.pull_request.draft
        != true) && inputs.run-prettier != 'false'
      uses: ./.github-actions-source/.github/actions/prettier
      with:
        changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
        setup-runtime: "false"
        package-manager: ${{ inputs.package-manager }}

    - name: Run Markdown check
      if:
        (github.event_name != 'pull_request' || github.event.pull_request.draft
        != true) && inputs.run-markdown != 'false'
      uses: ./.github-actions-source/.github/actions/markdown-check
      with:
        changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
        setup-runtime: "false"
        package-manager: ${{ inputs.package-manager }}

    - name: Run Commit check
      if:
        (github.event_name != 'pull_request' || github.event.pull_request.draft
        != true) && inputs.run-commits != 'false'
      uses: ./.github-actions-source/.github/actions/commit-check
      with:
        setup-runtime: "false"
        package-manager: ${{ inputs.package-manager }}
