name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  checks:
    steps:
      - uses: teodorus-nathaniel/personal-actions/.github/workflows/pr-checks.yml@0389f1d0d0d731fc2fd31ab7b1e751ffa5b7c230
