name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: teodorus-nathaniel/personal-actions/.github/actions/pr-checks@0389f1d0d0d731fc2fd31ab7b1e751ffa5b7c230
