name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: teodorus-nathaniel/personal-actions/.github/actions/pr-checks@81b0df0ad49b9a4b40f320cc3a1dd63a1cd0c4fa
